# Generated by Django 5.1.1 on 2024-10-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amazon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custid', models.IntegerField()),
                ('custname', models.CharField(max_length=20)),
                ('custaddr', models.CharField(max_length=20)),
                ('custphnno', models.IntegerField()),
            ],
        ),
    ]
